//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PersonelMVCUI.Models.EntityFramework
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Personel
    {
        public int Id { get; set; }
        [Display(Name = "Departman Adý")]
        [Required(ErrorMessage = "Departman adýný boþ býrakamazsýnýz.")]
        public Nullable<int> DepartmanId { get; set; }
        [Required(ErrorMessage = "Adý boþ býrakamazsýnýz.")]
        public string Ad { get; set; }
        [Required(ErrorMessage = "Soyadý boþ býrakamazsýnýz.")]
        public string Soyad { get; set; }
        [Required(ErrorMessage = "Maaþý boþ býrakamazsýnýz.")]
        [Range(4253, 1000000, ErrorMessage = "Maaþ asgari ücretten düþük olamaz.")]
        public Nullable<short> Maas { get; set; }
        [Display(Name = "Doðum Tarihi")]
        [Required(ErrorMessage = "Doðum tarihini boþ býrakamazsýnýz.")]
        public Nullable<System.DateTime> DogumTarihi { get; set; }
        [Required(ErrorMessage = "Cinsiyeti boþ býrakamazsýnýz.")]
        public bool Cinsiyet { get; set; }
        public bool EvliMi { get; set; }
    
        public virtual Departman Departman { get; set; }
    }
}
